kind: pipeline
type: docker
name: MINHA PIPE


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request

steps:
- name: build-push
  image: harbor.appwebdiario.com.br/appwebdiario/docker-build:latest
  volumes:
  - name: dockersock
    path: /var/run
  privileged: true
  commands:
  - sleep 5 ## give docker enough time to start
  - docker build -t harbor.appwebdiario.com.br/appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7} .
  - docker push harbor.appwebdiario.com.br/appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}

- name: delivery
  image: harbor.appwebdiario.com.br/appwebdiario/pipeline-base-module:latest
  environment:
    GITOPS_IMAGE_TAG: ${DRONE_COMMIT_SHA:0:7}
    GITOPS_YAML_FILE: application.yml

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  command:
    [
      '--insecure-registry=harbor.appwebdiario.com.br'
    ]
volumes:
- name: dockersock
  temp: {}
