kind: pipeline
type: kubernetes
name: MINHA PIPE


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request


###################################################   build-push
steps:
- name: build-push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  privileged: true
  commands:
  - sleep 5 ## give docker enough time to start
  - docker login -u deployer -p D3ployer harbor.appwebdiario.com.br
  - docker build  -t appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7} .
  - docker push harbor.appwebdiario.com.br/appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}


######################################################   Delivery
- name: delivery
  image: harbor.appwebdiario.com.br/appwebdiario/plugin-drone:latest
  commands:
  - git clone git@github.com:appwebdiario/deploy-applications.git
  - cd deploy-applications
  - sed -E -i.bak 's%(appwebdiario/poc-site:).*%appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}%' site-helm/templates/uzi-poc-site-deployment.yml
  - git add . && git commit -m "Change image site-poc to appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}" && git push


########################################################   Services
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
volumes:
- name: dockersock
  temp: {}
