kind: pipeline
type: kubernetes
name: MINHA PIPE


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request

###################################################   build-push
steps:
- name: build-push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  privileged: true
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  commands:
  - sleep 5 ## give docker enough time to start
  - echo "${PASSWORD}" | docker login -u "${USERNAME}" harbor.appwebdiario.com.br --password-stdin
  - docker build -t harbor.appwebdiario.com.br/appwebdiario/site:${DRONE_COMMIT_SHA:0:7} .
  - docker push harbor.appwebdiario.com.br/appwebdiario/site:${DRONE_COMMIT_SHA:0:7}

######################################################   Delivery
- name: delivery
  image: harbor.appwebdiario.com.br/appwebdiario/pipeline-base-module:latest
  pull: always
  environment:
    GITOPS_IMAGE_TAG: ${DRONE_COMMIT_SHA:0:7}
    GITOPS_YAML_FILE: application.yml

########################################################   Services
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  command:
    [
      '--insecure-registry=harbor.appwebdiario.com.br'
    ]
volumes:
- name: dockersock
  temp: {}
