kind: pipeline
type: kubernetes
name: MINHA PIPE


######################################################   trigger
trigger:
  branch:
  - main
  when:
    event:
      exclude:
      - pull_request


###################################################   build-push
steps:
- name: build-push
  image: harbor.appwebdiario.com.br/appwebdiario/docker-build:1.0
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    APP_NAME: poc-site


######################################################   Delivery
- name: delivery
  image: harbor.appwebdiario.com.br/appwebdiario/plugin-drone:latest
  commands:
  - git clone git@github.com:tiagoaramos/deploy-applications.git
  - cd deploy-applications
  - sed -E -i.bak 's%(harbor.appwebdiario.com.br/appwebdiario/poc-site:).*%harbor.appwebdiario.com.br/appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}%' site-helm/templates/uzi-poc-site-deployment.yml
  - git add . && git commit -m "Change image site-poc to harbor.appwebdiario.com.br/appwebdiario/poc-site:${DRONE_COMMIT_SHA:0:7}" && git push


########################################################   Services
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  command:
    [
      '--insecure-registry=harbor.appwebdiario.com.br'
    ]
volumes:
- name: dockersock
  temp: {}
