name: site
namespace: site
containerPort: 80
replicaCount: 2

# Variáveis de ambiente da aplicação
env:
  SPRING_PROFILES_ACTIVE: production # Production ou Homolog
  SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/site
  SPRING_DATASOURCE_USERNAME: myapp
  SPRING_DATASOURCE_PASSWORD: myapp123
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: 6379
  SPRING_REDIS_PASSWORD: redis123
  LOG_LEVEL: INFO

# Configuração de health check
healthCheckPath: /
initialDelaySeconds: 5

infra:
  - type: ingress
    host:
      - host: site.appwebdiario.com.br
      - host: site.appwebdiario.local
