name: site
namespace: site
containerPort: 80
replicaCount: 2

# Variáveis de ambiente da aplicação
env:
  SPRING_PROFILES_ACTIVE: production # Production ou Homolog
  LOG_LEVEL: INFO


# Configuração de health check
healthCheckPath: /
initialDelaySeconds: 5

infra:
  - type: ingress
    host:
      - host: site.appwebdiario.com.br
      - host: site.appwebdiario.local
